
services:
  # Django バックエンド
  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000

  # React フロントエンド
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: npm start
